version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    # Check for updates once a day
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
