builds:
  - binary: grpcurl
    main: ./cmd/grpcurl/grpcurl.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: x86_64
    386: x86_32
    darwin: osx
  files:
    - LICENSE
