builds:
  - binary: grpcurl
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: x64
    386: x86
    darwin: osx
